/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hospital;

import Login.Login;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import java.util.*; 
import javax.swing.table.DefaultTableModel;
import CommunityAdmin.CommunityAdmin;
import Patient.Patient;
import SystemAdmin.SystemAdmin;
import java.util.regex.Matcher;
import java.util.regex.Pattern;






/**
 *
 * @author lance
 */
public class Hospital extends javax.swing.JFrame {
private JFrame frame;
    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
    this.setResizable(false);
    Toolkit tk = Toolkit.getDefaultToolkit();
    int xsize = (int) tk.getScreenSize().getWidth();
    int ysize = (int) tk.getScreenSize().getHeight(); 
    Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration()); 
    int taskBarSize = scnMax.bottom;
    this.setSize(xsize, ysize - taskBarSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        JBtnExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtDose = new javax.swing.JTextField();
        jtxtIssuedDate = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jtxtLot = new javax.swing.JTextField();
        jtxtNumberTablets = new javax.swing.JTextField();
        jtxtRef = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtDrivingUsingMachines = new javax.swing.JTextField();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jtextDOB = new javax.swing.JTextField();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtHowToUseMedication = new javax.swing.JTextField();
        jtxtMoreInformation = new javax.swing.JTextField();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jtxtSideEffects = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel45 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2000, 800));
        setPreferredSize(new java.awt.Dimension(2000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel2.setText("Medical Assistance System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1390, 100));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 400, 520));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton1.setBackground(new java.awt.Color(51, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 0, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 0, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton1");

        jButton7.setText("jButton1");

        jButton8.setText("jButton1");

        jButton9.setBackground(new java.awt.Color(51, 0, 153));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Reset");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(51, 0, 153));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Prescription");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        JBtnExit.setBackground(new java.awt.Color(51, 0, 153));
        JBtnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBtnExit.setForeground(new java.awt.Color(255, 255, 255));
        JBtnExit.setText("Exit");
        JBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1774, 1774, 1774)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(301, 301, 301))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10)
                            .addComponent(JBtnExit)
                            .addComponent(jButton9)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1400, 70));

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Patient Prescription");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1000, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Medication:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Blood Pressure", "Body temperature", "Pulse Rate", "Respiration Rate" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 230, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Vital Sign:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Number of units:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Dose (mg):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Issue Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Rate/ value:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Daily Dose:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Expiry Date:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jtxtExpDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 230, -1));

        jtxtDose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 230, -1));

        jtxtIssuedDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 230, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 230, -1));

        jtxtLot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 230, -1));

        jtxtNumberTablets.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtNumberTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumberTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 230, -1));

        jtxtRef.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 230, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Storage Tips:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("More Information:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Use of Medication:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Driving and Using:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Next Visit :");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Patient ID:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Date of Birth:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Patient Name:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        jtxtPatientName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtPatientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPatientNameKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 230, -1));

        jtxtDrivingUsingMachines.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtDrivingUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 230, -1));

        jtxtDoctorNHSNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtDoctorNHSNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtDoctorNHSNoKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 230, -1));

        jtextDOB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtextDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtextDOBKeyReleased(evt);
            }
        });
        getContentPane().add(jtextDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 230, -1));

        jtxtPatientID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtPatientID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPatientIDKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 230, -1));

        jtxtHowToUseMedication.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtHowToUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 230, -1));

        jtxtMoreInformation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtMoreInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 230, -1));

        jtxtStorageAdvice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 230, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Side Effects:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jtxtSideEffects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 230, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Patient Address:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, -1, -1));

        jtxtAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 600, 230, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Medicine", "Ref Number", "Dose (mg)", "Number of Units", "LOT", "Issue date", "Expiry Date", "Daily dose", "Side Effects", "More Information", "Storage Tips", "Driving and Using", "How to use", "Patient Id", "NHS Number", "Patient name", "Date of Birth", "Patient Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 1390, 290));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, 90, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 90, 20));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 90, 20));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem().equals("Blood Pressure"))
        {
            jtxtRef.setText("Ibuprofen");
            jtxtDose.setText("2");
            jtxtNumberTablets.setText ("32");
           // jtxtLot.setText("561005875");
            jtxtIssuedDate.setText("06/05/20222");
            jtxtExpDate.setText ("04/05/2024");
            jtxtDailyDose.setText("4");
            jtxtSideEffects. setText ("Bleeding");
            jtxtMoreInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDrivingUsingMachines.setText ("No") ;
            jtxtHowToUseMedication.setText("Use water, No Alcohol");
           // jtxtPatientID. setText ("P9589454");
           // jtxtDoctorNHSNo.setText ("646564") ;
                    }
        
        else if(jComboBox1.getSelectedItem().equals("Body temperature"))
        {
            jtxtRef.setText("Paracetamol");
            jtxtDose.setText("5");
            jtxtNumberTablets.setText ("20");
           // jtxtLot.setText("561008956");
            jtxtIssuedDate.setText("06/05/2022");
            jtxtExpDate.setText ("04/05/2024");
            jtxtDailyDose.setText("4");
            jtxtSideEffects. setText ("Headache");
            jtxtMoreInformation.setText("Place Dispensary");
            jtxtStorageAdvice.setText("Less than 40%");
            jtxtDrivingUsingMachines.setText ("No") ;
            jtxtHowToUseMedication.setText("Use water or Alcohol");
            //jtxtPatientID. setText ("s453667");
            //jtxtDoctorNHSNo.setText ("8986885") ;
                  }
        
        else if(jComboBox1.getSelectedItem().equals("Respiration Rate"))
        {
            jtxtRef.setText("Ondem");
            jtxtDose.setText("4");
            jtxtNumberTablets.setText ("10");
            //jtxtLot.setText("265008956");
            jtxtIssuedDate.setText("06/05/2022");
            jtxtExpDate.setText ("04/05/2024");
            jtxtDailyDose.setText("1");
            jtxtSideEffects. setText ("Nausea");
            jtxtMoreInformation.setText("No Sunlight");
            jtxtStorageAdvice.setText("Less than 80%");
            jtxtDrivingUsingMachines.setText ("No") ;
            jtxtHowToUseMedication.setText("Use water or Alcohol");
           // jtxtPatientID. setText ("O252667");
           // jtxtDoctorNHSNo.setText ("4545885") ;
                    }
        
         else if(jComboBox1.getSelectedItem().equals("Pulse Rate"))
        {
            jtxtRef.setText("Amlopdopine");
            jtxtDose.setText("6");
            jtxtNumberTablets.setText ("50");
            //jtxtLot.setText("7898956");
            jtxtIssuedDate.setText("06/05/2022");
            jtxtExpDate.setText ("04/05/2024");
            jtxtDailyDose.setText("8");
            jtxtSideEffects. setText ("Cough");
            jtxtMoreInformation.setText("No refrigeration");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDrivingUsingMachines.setText ("No") ;
            jtxtHowToUseMedication.setText("Use water or Alcohol");
            //jtxtPatientID. setText ("a08943667");
            //jtxtDoctorNHSNo.setText ("6745434") ;
                    }
        else 
        {
            jtxtRef.setText("");
            jtxtDose.setText("");
            jtxtNumberTablets.setText ("");
            //jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText ("");
            jtxtDailyDose.setText("");
            jtxtSideEffects. setText ("");
            jtxtMoreInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtDrivingUsingMachines.setText ("") ;
            jtxtHowToUseMedication.setText("");
            //jtxtPatientID. setText ("");
            ///jtxtDoctorNHSNo.setText ("") ;
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jtxtNumberTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumberTabletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumberTabletsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow() ==-1){
        if(jTable1.getRowCount() ==0) {
            
        JOptionPane.showMessageDialog(null, "No data to delete", "Hospital Management Systems",
        JOptionPane.OK_OPTION );
        
        }else{
            JOptionPane.showMessageDialog (null, "Select a row to delete", "Hospital Management Systems",
        JOptionPane. OK_OPTION);
        }
        
        }
        else
        {
        model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            jtxtRef.setText("");
            jComboBox1.getModel().setSelectedItem("Make a Selection");
            jtxtDose.setText("");
            jtxtNumberTablets.setText ("");
            jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText ("");
            jtxtDailyDose.setText("");
            jtxtSideEffects. setText ("");
            jtxtMoreInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtDrivingUsingMachines.setText ("") ;
            jtxtHowToUseMedication.setText("");
            jtxtPatientID. setText ("");
            jtxtDoctorNHSNo.setText ("") ;
            jtxtPatientName.setText ("") ;
            jtextDOB.setText ("") ;
            jtxtAddress.setText ("") ;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void JBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnExitActionPerformed
            frame = new JFrame();
            if (JOptionPane.showConfirmDialog( frame, "Confirm if you want to exit", "HospitalManagement System",
                    JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
            {System.exit(0);
            }
    }//GEN-LAST:event_JBtnExitActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
String Qty1 = (jtxtRef.getText());
String Qty2 = (jtxtDose.getText());
String Qty3 = (jtxtNumberTablets.getText());
String Qty4 = (jtxtLot.getText());
String Qty5 = (jtxtDailyDose.getText());
String Qty6 = (jtxtSideEffects.getText());
String Qty7 = (jtxtMoreInformation.getText());
String Qty8 = (jtxtHowToUseMedication.getText());
String Qty9 = (jtxtPatientID.getText());
String Qty10 = (jtxtPatientName.getText());
String Qty11 = (jtxtAddress.getText());
String Qty12 = (jtextDOB.getText());
String Qty13 =  "";        

if(jComboBox1.getSelectedItem().equals("IbuProfen"))
{
Qty13 ="IbuProfen";
}
else if (jComboBox1.getSelectedItem().equals("Paracetamol"))
{
Qty13 ="Paracetamol";
   }
else if (jComboBox1.getSelectedItem().equals("Ondem"))
{
Qty13= "Ondem";
   }

else if (jComboBox1.getSelectedItem().equals("Amlodapine"))
{
Qty13= "Amlodapine";
   }

jTextArea1.setText("");
jTextArea1.append("\t\n\tMedical Assistance Systems\n"
+"\nPatient Name:\t\t"+ Qty10 
+"\nDate of Birth:\t\t" +Qty12
+"\nPatient Address :\t" + Qty11 
+"\nMedication:\t\t" + Qty1
+"\nDose (mg) :\t\t"+ Qty2 
+"\nNumber of Units :\t" + Qty3 
+"\nRate: \t\t" + Qty4 
+"\nDaily Dose: \t\t"+ Qty5 
+"\nSide Effects :\t\t" +Qty6 
+"\nMore Information :\t"+Qty7 
+"\nHow to Use Medication :\t"+Qty8 
+"\nPatient ID:\t\t" + Qty9 
+"\n\nPatient Instruction: For Emergency call 911 \nToll free number available for booking an appointment \n" 
+"TEXT REMINDERS FOR APPOINTMENT AVAILABLE");

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow (new Object[] {jComboBox1.getSelectedItem().toString(),
        jtxtRef.getText(), jtxtDose.getText(), jtxtNumberTablets.getText(), jtxtLot.getText (),
        jtxtIssuedDate.getText(), jtxtExpDate.getText(), jtxtDailyDose.getText(),
        jtxtSideEffects.getText(), jtxtMoreInformation.getText(), jtxtStorageAdvice.getText(),
         jtxtDrivingUsingMachines.getText(),
        jtxtHowToUseMedication.getText(),
        jtxtPatientID.getText(), jtxtDoctorNHSNo.getText(),jtxtPatientName.getText(), jtextDOB.getText(), jtxtAddress.getText(), });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     this.setVisible(false);   
        Login iLogin = new Login();
                    iLogin.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtextDOBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextDOBKeyReleased
        String PATTERN = "^([0-2][0-9]||3[0-1])/(0[0-9]||1[0-2])/([0-9][0-9])?[0-9][0-9]$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(jtextDOB.getText());
        if(!match.matches()){
        jLabel11.setText("DD/MM/YYYY!!");
               
        }
        else{
            jLabel11.setText("");
        }
    }//GEN-LAST:event_jtextDOBKeyReleased

    private void jtxtPatientNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPatientNameKeyReleased
char c = evt.getKeyChar();
     if (Character.isDigit(c)){
         jtxtPatientName.setEditable(false);
         
         jLabel45.setText("Invalid Name!");
     }
     else
     {
     jLabel45.setText( null);
     jtxtPatientName.setEditable(true);
     }        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPatientNameKeyReleased

    private void jtxtDoctorNHSNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDoctorNHSNoKeyReleased
       String PATTERN = "^([0-2][0-9]||3[0-1])/(0[0-9]||1[0-2])/([0-9][0-9])?[0-9][0-9]$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(jtxtDoctorNHSNo.getText());
        if(!match.matches()){
        jLabel46.setText("DD/MM/YYYY!!");
               
        }
        else{
            jLabel46.setText("");
        }
    }//GEN-LAST:event_jtxtDoctorNHSNoKeyReleased

    private void jtxtPatientIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPatientIDKeyReleased
  
 String PATTERN = "\\d+";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(jtxtPatientID.getText());
        if(!match.matches()){
        jLabel47.setText("Only Digits");
               
        }
        else{
            jLabel47.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jtxtPatientIDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jtextDOB;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingUsingMachines;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtHowToUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtMoreInformation;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtSideEffects;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
